all: AbstractBinaryTree.java BinaryTree.java Tester.java
	javac -Xlint *.java

run: AbstractBinaryTree.class BinaryTree.class Tester.class
	java Tester

clean: AbstractBinaryTree.class BinaryTree.class Tester.class
	rm *.class